[package]
name = "angular-units"
version = "0.1.0"
description = "A library for representing and manipulating angular quantities in various units."
authors = ["tylerreisinger <reisinger.tyler@gmail.com>"]
repository = "https://github.com/tylerreisinger/rust-angular-units"
homepage = "https://github.com/tylerreisinger/rust-angular-units"
documentation = "https://tylerreisinger.github.io/rust-angular-units"
readme = "README.md"
keywords = ["angle", "angular", "units", "mathematics"]
license = "MIT"

[features]
default = ["approx"]

[dependencies]
num = "^0.1"

[dependencies.approx]
version = "^0.1"
optional = true
