[package]
name = "angular-units"
version = "0.1.0"
authors = ["tylerreisinger <reisinger.tyler@gmail.com>"]
repository = "https://github.com/tylerreisinger/rust-angular-units"
homepage = "https://github.com/tylerreisinger/rust-angular-units"
readme = "README.md"
keywords = ["angle", "angular", "units", "mathematics"]
license = "MIT"

[dependencies]
num = "0.1"
approx = "0.1"
